<script setup lang="ts">
import { ArrowDown, ArrowUp, GripVertical, Plus, Trash2 } from 'lucide-vue-next'
import type { ArticleBlock } from '~/shared/article-localization'
import { insertArticleBlock, moveArticleBlock } from '~/shared/article-block-editor'

const props = withDefaults(defineProps<{ modelValue: ArticleBlock[]; folder?: string; errors?: Record<string, string> }>(), { folder: 'articles', errors: () => ({}) })
const emit = defineEmits<{ 'update:modelValue': [ArticleBlock[]] }>()
const draggingIndex = ref<number | null>(null)
const blockOptions: Array<{ type: ArticleBlock['type']; label: string }> = [
  { type: 'paragraph', label: 'Paragraph' }, { type: 'heading', label: 'Heading' }, { type: 'image', label: 'Image' },
  { type: 'blockquote', label: 'Quote' }, { type: 'list', label: 'List' }, { type: 'callout', label: 'Callout' },
]
function update(next: ArticleBlock[]) { emit('update:modelValue', next) }
function set(index: number, block: ArticleBlock) { const next = [...props.modelValue]; next[index] = block; update(next) }
function insert(type: ArticleBlock['type'], index = props.modelValue.length) { update(insertArticleBlock(props.modelValue, type, index)) }
function remove(index: number) { const next = [...props.modelValue]; next.splice(index, 1); update(next) }
function move(from: number, to: number) { update(moveArticleBlock(props.modelValue, from, to)) }
function onDrop(target: number) { if (draggingIndex.value !== null) move(draggingIndex.value, target); draggingIndex.value = null }
function autoGrow(event: Event) { const el = event.target as HTMLTextAreaElement; el.style.height = 'auto'; el.style.height = `${Math.min(Math.max(el.scrollHeight, 96), 640)}px` }
function setImageDefaults(index: number, dimensions: { width: number; height: number }) { const block = props.modelValue[index]; if (block?.type === 'image') set(index, { ...block, displaySize: dimensions.width > dimensions.height * 1.1 ? 'wide' : 'medium', aspectRatio: block.aspectRatio ?? 'auto' }) }
function label(block: ArticleBlock) { return block.type === 'heading' ? `H${block.level ?? 2}` : block.type }
</script>

<template>
  <section class="space-y-3" aria-label="Body blocks editor">
    <div class="sticky top-3 z-20 rounded-xl border border-neutral-line bg-white/95 p-3 shadow-sm backdrop-blur"><div class="flex flex-wrap items-center gap-2"><span class="mr-auto text-sm font-semibold">Body Blocks</span><button v-for="option in blockOptions" :key="option.type" type="button" class="inline-flex min-h-9 items-center gap-1 rounded-full border border-neutral-line px-3 text-xs font-semibold hover:border-brand-green/40" @click="insert(option.type)"><Plus class="h-3.5 w-3.5" aria-hidden="true" />{{ option.label }}</button></div></div>
    <div v-for="(block, index) in modelValue" :key="index" class="group relative">
      <div v-if="index > 0" class="relative flex h-5 items-center justify-center"><details class="absolute z-10"><summary class="flex h-7 w-7 cursor-pointer list-none items-center justify-center rounded-full border border-neutral-line bg-white text-brand-green opacity-0 shadow-sm transition-opacity group-hover:opacity-100 focus:opacity-100" :aria-label="`Sisipkan block sebelum nomor ${index + 1}`"><Plus class="h-4 w-4" /></summary><div class="absolute left-1/2 top-8 flex -translate-x-1/2 gap-1 rounded-xl border border-neutral-line bg-white p-2 shadow-lg"><button v-for="option in blockOptions" :key="option.type" type="button" class="whitespace-nowrap rounded-full px-2 py-1 text-xs hover:bg-neutral-soft" @click="insert(option.type, index)">{{ option.label }}</button></div></details></div>
      <article class="rounded-xl border border-neutral-line bg-white p-3" :class="draggingIndex === index ? 'opacity-50' : ''" @dragover.prevent @drop="onDrop(index)">
        <header class="flex flex-wrap items-center gap-2 border-b border-neutral-line pb-2"><span class="w-7 text-xs font-bold tabular-nums text-neutral-charcoal/45">{{ String(index + 1).padStart(2, '0') }}</span><button type="button" draggable="true" class="cursor-grab rounded p-1 text-neutral-charcoal/45 hover:bg-neutral-soft" :aria-label="`Seret block ${index + 1}`" title="Seret untuk mengurutkan" @dragstart="draggingIndex = index" @dragend="draggingIndex = null"><GripVertical class="h-4 w-4" /></button><span class="mr-auto text-xs font-semibold uppercase tracking-[0.12em] text-gold">{{ label(block) }}</span><button type="button" class="rounded p-1 disabled:opacity-30" :disabled="index === 0" :aria-label="`Pindahkan block ${index + 1} ke atas`" title="Pindah ke atas" @click="move(index, index - 1)"><ArrowUp class="h-4 w-4" /></button><button type="button" class="rounded p-1 disabled:opacity-30" :disabled="index === modelValue.length - 1" :aria-label="`Pindahkan block ${index + 1} ke bawah`" title="Pindah ke bawah" @click="move(index, index + 1)"><ArrowDown class="h-4 w-4" /></button><button type="button" class="rounded p-1 text-red-700" :aria-label="`Hapus block ${index + 1}`" title="Hapus block" @click="remove(index)"><Trash2 class="h-4 w-4" /></button></header>
        <textarea v-if="['paragraph','blockquote','callout'].includes(block.type)" :data-field="`body-${index}`" :value="block.text" rows="3" class="mt-3 min-h-24 w-full resize-y overflow-y-auto rounded-lg border px-3 py-2 text-sm" :class="errors[`body-${index}`] ? 'border-red-400' : 'border-neutral-line'" @input="autoGrow($event); set(index, { ...block, text: ($event.target as HTMLTextAreaElement).value })" />
        <div v-else-if="block.type === 'heading'" class="mt-3 grid gap-2 sm:grid-cols-[80px_1fr]"><select :value="block.level" class="rounded-lg border border-neutral-line px-2" @change="set(index, { ...block, level: Number(($event.target as HTMLSelectElement).value) as 2|3 })"><option :value="2">H2</option><option :value="3">H3</option></select><input :data-field="`body-${index}`" :value="block.text" class="rounded-lg border border-neutral-line px-3" @input="set(index, { ...block, text: ($event.target as HTMLInputElement).value })" /></div>
        <div v-else-if="block.type === 'list'" class="mt-3"><select :value="String(block.ordered)" class="rounded-lg border border-neutral-line px-2 py-1 text-xs" @change="set(index, { ...block, ordered: ($event.target as HTMLSelectElement).value === 'true' })"><option value="false">Bullet</option><option value="true">Numbered</option></select><textarea :value="(block.items ?? []).join('\n')" rows="3" class="mt-2 min-h-24 w-full rounded-lg border border-neutral-line px-3 py-2 text-sm" @input="autoGrow($event); set(index, { ...block, items: ($event.target as HTMLTextAreaElement).value.split('\n') })" /></div>
        <div v-else-if="block.type === 'image'" class="mt-3 space-y-3"><MediaImageUploader :model-value="block.src" :folder="folder" label="Body image" @update:model-value="set(index, { ...block, src: $event })" @update:file-id="set(index, { ...block, fileId: $event })" @update:dimensions="setImageDefaults(index, $event)" /><div class="grid gap-3 sm:grid-cols-2"><label class="text-xs font-semibold">Ukuran Tampilan<select :value="block.displaySize ?? 'full'" class="mt-1 w-full rounded-lg border border-neutral-line px-3 py-2 text-sm" @change="set(index, { ...block, displaySize: ($event.target as HTMLSelectElement).value as ArticleBlock['displaySize'] })"><option value="small">Kecil</option><option value="medium">Sedang</option><option value="wide">Lebar</option><option value="full">Penuh</option></select></label><label class="text-xs font-semibold">Proporsi<select :value="block.aspectRatio ?? 'auto'" class="mt-1 w-full rounded-lg border border-neutral-line px-3 py-2 text-sm" @change="set(index, { ...block, aspectRatio: ($event.target as HTMLSelectElement).value as ArticleBlock['aspectRatio'] })"><option value="auto">Otomatis</option><option value="16:9">Landscape 16:9</option><option value="4:5">Portrait 4:5</option><option value="1:1">Square 1:1</option></select></label></div><input :value="block.alt" placeholder="Alt text" class="w-full rounded-lg border border-neutral-line px-3 py-2 text-sm" @input="set(index, { ...block, alt: ($event.target as HTMLInputElement).value })" /><input :value="block.caption" placeholder="Caption (opsional)" class="w-full rounded-lg border border-neutral-line px-3 py-2 text-sm" @input="set(index, { ...block, caption: ($event.target as HTMLInputElement).value })" /></div>
        <p v-if="errors[`body-${index}`]" class="mt-1 text-xs text-red-700">{{ errors[`body-${index}`] }}</p>
      </article>
    </div>
  </section>
</template>
