import { and, asc, count, desc, eq, ilike, or, sql } from 'drizzle-orm'
import { articleFeedback, articles } from '../db/schema'
import type { DbLike } from '../db'

type Filters = { search?: string; city?: string; category?: string; sort?: string; limit?: number; offset?: number }
function articleWhere(f: Filters) { const c=[]; if(f.city)c.push(eq(articles.city,f.city)); if(f.category)c.push(eq(articles.category,f.category)); if(f.search)c.push(or(ilike(articles.title,`%${f.search}%`),ilike(articles.slug,`%${f.search}%`))); return c.length?and(...c):undefined }
function orderFor(sort?: string) { if(sort==='total')return desc(sql`count(${articleFeedback.id})`); if(sort==='helpful')return desc(sql`count(*) filter (where ${articleFeedback.value} = 'HELPFUL')`); if(sort==='ratio')return desc(sql`case when count(${articleFeedback.id}) = 0 then 0 else count(*) filter (where ${articleFeedback.value} = 'HELPFUL')::numeric / count(${articleFeedback.id}) end`); return asc(sql`case when count(${articleFeedback.id}) = 0 then 1 else 0 end`), desc(sql`count(*) filter (where ${articleFeedback.value} = 'NOT_HELPFUL')`), desc(articles.updatedAt) }
export async function listArticleFeedback(db:DbLike,f:Filters){const q=db.select({article:articles,helpful:sql<number>`count(*) filter (where ${articleFeedback.value} = 'HELPFUL')`,notHelpful:sql<number>`count(*) filter (where ${articleFeedback.value} = 'NOT_HELPFUL')`,total:sql<number>`count(${articleFeedback.id})`}).from(articles).leftJoin(articleFeedback,eq(articleFeedback.articleId,articles.id)).where(articleWhere(f)).groupBy(articles.id).orderBy(orderFor(f.sort));if(f.limit!==undefined)q.limit(f.limit);if(f.offset!==undefined)q.offset(f.offset);return q}
export async function countFeedbackArticles(db:DbLike,f:Omit<Filters,'sort'|'limit'|'offset'>){const r=await db.select({value:count()}).from(articles).where(articleWhere(f));return Number(r[0]?.value??0)}
export async function getArticleFeedbackSummary(db:DbLike,articleId:number){const r=await db.select({helpful:sql<number>`count(*) filter (where ${articleFeedback.value} = 'HELPFUL')`,notHelpful:sql<number>`count(*) filter (where ${articleFeedback.value} = 'NOT_HELPFUL')`,total:sql<number>`count(${articleFeedback.id})`}).from(articleFeedback).where(eq(articleFeedback.articleId,articleId));return {helpful:Number(r[0]?.helpful??0),notHelpful:Number(r[0]?.notHelpful??0),total:Number(r[0]?.total??0)}}
export async function createArticleFeedback(db:DbLike,articleId:number,value:string){const r=await db.insert(articleFeedback).values({articleId,value}).returning();return r[0]}

export async function getFeedbackAggregate(db:DbLike,f:Filters){const r=await db.select({helpful:sql<number>`count(*) filter (where ${articleFeedback.value} = 'HELPFUL')`,notHelpful:sql<number>`count(*) filter (where ${articleFeedback.value} = 'NOT_HELPFUL')`,total:sql<number>`count(${articleFeedback.id})`}).from(articles).leftJoin(articleFeedback,eq(articleFeedback.articleId,articles.id)).where(articleWhere(f));const helpful=Number(r[0]?.helpful??0),notHelpful=Number(r[0]?.notHelpful??0);return {helpful,notHelpful,total:helpful+notHelpful}}
