import { and, asc, count, desc, eq, ilike, or, sql } from 'drizzle-orm'
import { galleryItems } from '../db/schema'
import type { DbLike } from '../db'

export type GalleryInput = { imageUrl: string; imageFileId?: string | null; altText: string; title?: string | null; description?: string | null; city: string; category: string; locationName?: string | null; latitude?: number | null; longitude?: number | null; tags: string[]; priority: number; status: string; takenAt?: Date | null; publishedAt?: Date | null }
type Filters = { search?: string; city?: string; category?: string; status?: string; tag?: string; limit?: number; offset?: number }
function whereFor(f: Filters) { const c = []; if (f.city) c.push(eq(galleryItems.city, f.city)); if (f.category) c.push(eq(galleryItems.category, f.category)); if (f.status) c.push(eq(galleryItems.status, f.status)); if (f.tag) c.push(sql`${galleryItems.tags} @> ${JSON.stringify([f.tag])}::jsonb`); if (f.search) c.push(or(ilike(galleryItems.title, `%${f.search}%`), ilike(galleryItems.altText, `%${f.search}%`), ilike(galleryItems.locationName, `%${f.search}%`))); return c.length ? and(...c) : undefined }
export async function listGallery(db: DbLike, f: Filters) { const q = db.select().from(galleryItems).where(whereFor(f)).orderBy(desc(galleryItems.priority), desc(galleryItems.publishedAt), desc(galleryItems.updatedAt)); if (f.limit !== undefined) q.limit(f.limit); if (f.offset !== undefined) q.offset(f.offset); return q }
export async function countGallery(db: DbLike, f: Omit<Filters, 'limit'|'offset'>) { const r = await db.select({ value: count() }).from(galleryItems).where(whereFor(f)); return Number(r[0]?.value ?? 0) }
export async function getGallery(db: DbLike, id: number) { const r = await db.select().from(galleryItems).where(eq(galleryItems.id,id)).limit(1); return r[0] ?? null }
export async function getPublishedGallery(db: DbLike, id: number) { const r = await db.select().from(galleryItems).where(and(eq(galleryItems.id,id),eq(galleryItems.status,'PUBLISHED'))).limit(1); return r[0] ?? null }
export async function createGallery(db: DbLike, input: GalleryInput) { const r = await db.insert(galleryItems).values({...input, latitude: input.latitude == null ? null : String(input.latitude), longitude: input.longitude == null ? null : String(input.longitude), publishedAt: input.status === 'PUBLISHED' ? input.publishedAt ?? new Date() : null, updatedAt: new Date()}).returning(); return r[0] }
export async function updateGallery(db: DbLike,id:number,input:GalleryInput) { const old=await getGallery(db,id); if(!old)return null; const publishedAt=input.status==='PUBLISHED' ? input.publishedAt ?? old.publishedAt ?? new Date() : null; const r=await db.update(galleryItems).set({...input, latitude: input.latitude == null ? null : String(input.latitude), longitude: input.longitude == null ? null : String(input.longitude), publishedAt,updatedAt:new Date()}).where(eq(galleryItems.id,id)).returning(); return r[0]??null }
export async function deleteGallery(db: DbLike,id:number) { const r=await db.delete(galleryItems).where(eq(galleryItems.id,id)).returning({id:galleryItems.id}); return r[0]??null }
