import { count, desc, eq } from 'drizzle-orm'
import { articles, guides, galleryItems, mapLocations, contributions, articleFeedback } from '../db/schema'
import type { DbLike } from '../db'
import { listArticleFeedback } from './article-feedback'
import { listContributions } from './contributions'
const n=(v:unknown)=>Number(v??0)
export async function getMediaDashboard(db:DbLike){
  const [articlePub,guidePub,galleryPub,locationsActive,newContrib,feedbackTotal,attentionRows,newContributions,draftArticles,draftGuides,recentArticles,recentGuides,recentGallery,recentLocations,recentContrib]=await Promise.all([
    db.select({value:count()}).from(articles).where(eq(articles.status,'PUBLISHED')),db.select({value:count()}).from(guides).where(eq(guides.status,'PUBLISHED')),db.select({value:count()}).from(galleryItems).where(eq(galleryItems.status,'PUBLISHED')),db.select({value:count()}).from(mapLocations).where(eq(mapLocations.isActive,true)),db.select({value:count()}).from(contributions).where(eq(contributions.status,'NEW')),db.select({value:count()}).from(articleFeedback),listArticleFeedback(db,{limit:20}),listContributions(db,{status:'NEW',limit:5}),db.select().from(articles).where(eq(articles.status,'DRAFT')).orderBy(desc(articles.updatedAt)).limit(5),db.select().from(guides).where(eq(guides.status,'DRAFT')).orderBy(desc(guides.updatedAt)).limit(5),db.select({id:articles.id,title:articles.title,updatedAt:articles.updatedAt}).from(articles).orderBy(desc(articles.updatedAt)).limit(3),db.select({id:guides.id,title:guides.title,updatedAt:guides.updatedAt}).from(guides).orderBy(desc(guides.updatedAt)).limit(3),db.select({id:galleryItems.id,title:galleryItems.title,updatedAt:galleryItems.updatedAt}).from(galleryItems).orderBy(desc(galleryItems.updatedAt)).limit(3),db.select({id:mapLocations.id,title:mapLocations.name,updatedAt:mapLocations.updatedAt}).from(mapLocations).orderBy(desc(mapLocations.updatedAt)).limit(3),db.select({id:contributions.id,title:contributions.subject,updatedAt:contributions.updatedAt}).from(contributions).orderBy(desc(contributions.updatedAt)).limit(3)
  ])
  const attention=attentionRows.map(r=>({...r,helpfulRatio:r.total?Math.round(Number(r.helpful)/Number(r.total)*100):0})).filter(r=>r.total>0&&(r.notHelpful>=3||r.helpfulRatio<70)).slice(0,5).map(r=>({id:r.article.id,title:r.article.title,notHelpful:r.notHelpful,helpfulRatio:r.helpfulRatio}))
  const activity=[...recentArticles.map(r=>({kind:'article',label:'Artikel diperbarui',title:r.title,time:r.updatedAt,to:`/media/articles` })),...recentGuides.map(r=>({kind:'guide',label:'Panduan diperbarui',title:r.title,time:r.updatedAt,to:'/media/guides'})),...recentGallery.map(r=>({kind:'gallery',label:'Foto Gallery diperbarui',title:r.title||'Tanpa judul',time:r.updatedAt,to:'/media/gallery'})),...recentLocations.map(r=>({kind:'location',label:'Lokasi diperbarui',title:r.title,time:r.updatedAt,to:'/media/locations'})),...recentContrib.map(r=>({kind:'contribution',label:'Kontribusi baru diterima',title:r.title||'Tanpa subjek',time:r.updatedAt,to:'/media/contributions'}))].sort((a,b)=>new Date(b.time).getTime()-new Date(a.time).getTime()).slice(0,10)
  return {summary:{articlesPublished:n(articlePub[0]?.value),guidesPublished:n(guidePub[0]?.value),galleryPublished:n(galleryPub[0]?.value),locationsActive:n(locationsActive[0]?.value),contributionsNew:n(newContrib[0]?.value),feedbackTotal:n(feedbackTotal[0]?.value)},attention:{contributions:newContributions.map(r=>({id:r.id,type:r.type,city:r.city,subject:r.subject,message:r.message,createdAt:r.createdAt})),feedback:attention,drafts:[...draftArticles.map(r=>({id:r.id,title:r.title,kind:'article',updatedAt:r.updatedAt})),...draftGuides.map(r=>({id:r.id,title:r.title,kind:'guide',updatedAt:r.updatedAt}))].sort((a,b)=>new Date(b.updatedAt).getTime()-new Date(a.updatedAt).getTime()).slice(0,5)},recentActivity:activity}
}
